### ISSUE TITLE
adding Code of Conduct page

### ISSUE THREAD

**Issue by jaidh01** [Akasxh/Terrain-Recognition#7]
Hi @Akasxh ,

I believe it would be beneficial to establish a Code of Conduct for our public repository. This would help maintain discipline and promote a respectful and inclusive community. I suggest using a framework like the one provided by the [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) as a basis for our own guidelines.

Request: - Kindly assign this issue to me and label it as gssoc24-extd and hacktoberfest and level.

**Comment by Akasxh** [comment]
I have added a contributing.md file you could look upto that, also if something crucial is missing please inform me

**Comment by jaidh01** [comment]
I suggest expanding the "Enforcement Guidelines" section to include sub-sections like Warning, Temporary Ban, and Permanent Ban. This would provide a clear structure for how different levels of violations are handled, detailing the consequences if someone falls into any of these categories. It can help ensure transparency and fairness in enforcement.

**Comment by Akasxh** [comment]
Please also add a section of guidline to how to contribute before all the other stuff
 
Should include:
- labels only provided once a person finishes the specific issue
-creating seperate issue for your own ide
-while making new model with minimal change please add V1 or V2 or whatever you're upgrading from and it should be a new file not editing the existing one. The existing one should go into the past architecture folder.
-while using different techniques the file should be named as such along with the needed Version number indicating it's 0 or whatever

-while developing if you're making your own model better also make it past architecture if there are good changes to see how you have evolved

- All the submissions on the model should include a zip file to the dataset and the downloaded model along with its accuracy percentage

-Create a new folder latest model for whatever new technique is used with highest accuracy using that particular technique.

-Only the model with highest accuracy to be displayed outside of past architecture and latest model.

- even if there's already a technique used, and a user thinks he can improve the accuracy he can create a seperate issue regarding that to get allocation of level labels on completion only if it's having better accuracy using the same technique.same person won't get points for this.

- while pushing a new model, there should be a readme with that specific models architecture and detailed discription on how things are working. This should always be included together with the newer model

Please add these rules and make them clear and concise while doing so.

Additionally make the folder of latest model which will have model of different technique with highest accuracy of that said technique.

Also propose how we should keep all the submissions readme, the model everything together so that if one is inspecting a said model he or she can find the particular readme for it nearby.

**Comment by Akasxh** [comment]
This issue is completed and merged.

**Comment by jaidh01** [comment]
Hi @Akasxh,
I hope you're doing well. I wanted to clarify an issue regarding the PR process based on the GSSOC guidelines. I opened an issue, but another contributor raised a PR for it before I could, even though they were not assigned to the issue.

As per the guidelines, only the assigned individual can raise a PR. Could you please confirm whether the issue is assigned to someone else? If it is, could you close the PR submitted by the other contributor?

Here’s a screenshot for your reference: 
![Screenshot (36)](https://github.com/user-attachments/assets/37756981-3d1c-482d-ad63-90638911bb2f)


Thanks for your help!

**Comment by Akasxh** [comment]
I see it was fault at my part, I'll reopen this issue and you could maybe add all the necessary gssoc guidelines needed in that contribution.md file.

I forgot about that part of the guidelines thanks for reminding.

Thank you.

**Comment by jaidh01** [comment]
Thank you, @Akasxh. I will update the file with all the necessary details you mentioned above.
Additionally, I request you to please add the `level 1` label to this issue so that there will be no issues with my GSSoC-extd.”

**Comment by jaidh01** [comment]
Sir @Akasxh I request you to please add the `level 1` label to this issue so that there will be no issues with my GSSoC-extd.

**Comment by Akasxh** [comment]
Done.
